# Generated by Django 4.1.5 on 2023-03-12 10:57

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_published', models.DateTimeField(verbose_name='date published')),
                ('article_image', models.ImageField(upload_to='images/')),
                ('article_content', django_summernote.fields.SummernoteTextField()),
                ('article_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_summernote.fields.SummernoteTextField()),
                ('published', models.DateTimeField()),
            ],
        ),
    ]
