# Generated by Django 4.0 on 2023-03-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_content',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
    ]
