# Generated by Django 4.0 on 2023-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_article_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
