# Generated by Django 4.1.7 on 2023-03-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_article_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
